/**
 * Represents the structure of a transaction PDF report.
 * 
 * @interface TransactionPDFReportType
 * 
 * @property {Array<string>} header - An array of strings representing the header of the report.
 * @property {Array<Array<string | number | Date>>} data - A 2D array where each sub-array represents a row of data in the report. Each element in the sub-array can be a string, number, or Date.
 * @property {Array<string>} footer - An array of strings representing the footer of the report.
 */
export interface TransactionPDFReportType {
	header: Array<string>;
	data: Array<Array<string | number | Date>>;
	footer: Array<string>;
}

/**
 * Represents the options for a template.
 */
export interface TemplateOptions {
	/**
	 * The date associated with the template.
	 */
	date: string;

	/**
	 * A function that operates on a table.
	 */
	tableOperator: () => void;
}

/**
 * Represents a message sent by the worker to indicate its status.
 * 
 * @interface WorkerMessage
 * 
 * @property {("processing" | "completed")} status - The current status of the worker.
 * @property {number} [progress] - Optional. The progress of the worker's task, represented as a percentage.
 * @property {string} [blobURL] - Optional. The URL of the blob generated by the worker.
 */
export interface WorkerMessage {
	status: "processing" | "completed";
	progress?: number;
	blobURL?: string;
}
